#![allow(dead_code)]

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub struct AllowedStateSaveCall {
    pub path: &'static str,
    pub containing_fn: &'static str,
    pub callee_family: &'static str,
    pub intent: &'static str,
    pub migration_phase: &'static str,
    pub reason: &'static str,
    pub evidence_line: usize,
}

pub const BASELINE_DIRECT_SAVE_COUNT: usize = 72;

macro_rules! allow {
    ($path:literal, $fn:literal, $callee:literal, $intent:literal, $phase:literal, $line:literal) => {
        AllowedStateSaveCall {
            path: $path,
            containing_fn: $fn,
            callee_family: $callee,
            intent: $intent,
            migration_phase: $phase,
            reason: concat!($path, "::", $fn, " => ", $intent),
            evidence_line: $line,
        }
    };
}

pub const ALLOWED_STATE_SAVE_CALLS: &[AllowedStateSaveCall] = &[
    allow!(
        "cli/adapters.rs",
        "seed_fake_e2e_state",
        "save_runtime_state",
        "FakeE2eSeed",
        "s1a_legacy_external",
        1035
    ),
    allow!(
        "cli/adapters.rs",
        "fake_shutdown",
        "save_runtime_state",
        "FakeE2eSeed",
        "s1a_legacy_external",
        1070
    ),
    allow!(
        "cli/mod.rs",
        "shutdown_with_transport_and_state",
        "save_team_scoped_state",
        "ShutdownTeam",
        "s1b_migrate_first",
        886
    ),
    allow!(
        "cli/mod.rs",
        "shutdown_with_transport_and_state",
        "save_runtime_state",
        "ShutdownTeam",
        "s1b_migrate_first",
        895
    ),
    allow!(
        "cli/mod.rs",
        "acknowledge_idle",
        "save_runtime_state",
        "IdleAck",
        "s1a_legacy_external",
        2544
    ),
    allow!(
        "cli/mod.rs",
        "promote_live_sibling_after_scoped_shutdown",
        "save_runtime_state",
        "PromoteLiveSiblingAfterShutdown",
        "s1b_migrate_first",
        3526
    ),
    allow!(
        "coordinator/conpty_shim.rs",
        "finalize",
        "save_runtime_state",
        "CoordinatorConptyShim",
        "s1a_legacy_external",
        426
    ),
    allow!(
        "coordinator/conpty_shim.rs",
        "mark_transport_unavailable",
        "save_runtime_state",
        "CoordinatorConptyShim",
        "s1a_legacy_external",
        674
    ),
    allow!(
        "coordinator/tick.rs",
        "tick",
        "save_team_scoped_state",
        "CoordinatorTick",
        "s1b_migrate_first",
        427
    ),
    // 0.5.36 (`.team/artifacts/supermarket-api-error-recovery-locate.md`
    // §7.3): post-save recovery step writes the recovery intent result
    // (attempts, status, last_error, blocked_reason) via a dedicated
    // intent so future S1b migration can route it independently.
    allow!(
        "coordinator/steps/abnormal.rs",
        "write_recovery_intent_result",
        "save_runtime_state",
        "CoordinatorApiErrorRecovery",
        "s1a_legacy_external",
        1921
    ),
    allow!(
        "leader/lease.rs",
        "write_lease_dual_state",
        "save_runtime_state",
        "ClaimLeader",
        "s1b_migrate_first",
        1625
    ),
    allow!(
        "leader/lease.rs",
        "save_claim_team_scoped_state",
        "save_runtime_state",
        "ClaimLeader",
        "s1b_migrate_first",
        1702
    ),
    allow!(
        "leader/start.rs",
        "persist_managed_leader_binding",
        "save_runtime_state",
        "LeaderStartBinding",
        "s1a_legacy_external",
        795
    ),
    allow!(
        "leader/start.rs",
        "persist_exec_provider_leader_binding",
        "save_runtime_state",
        "LeaderStartBinding",
        "s1a_legacy_external",
        903
    ),
    allow!(
        "leader/start.rs",
        "persist_external_leader_topology_marker",
        "save_runtime_state",
        "LeaderStartBinding",
        "s1a_legacy_external",
        946
    ),
    // 0.5.35 (`.team/artifacts/managed-leader-provider-reentry-locate.md`
    // §5/§6): same-pane provider re-entry refresh writes canonical receiver
    // metadata via ownership::write_owner + save_runtime_state, matching
    // the LeaderStartBinding intent family (external ExecProvider
    // classification split).
    allow!(
        "leader/start.rs",
        "refresh_managed_leader_provider_binding",
        "save_runtime_state",
        "LeaderStartBinding",
        "s1a_legacy_external",
        1096
    ),
    allow!(
        "lifecycle/launch.rs",
        "save_launched_team_state_for_key",
        "save_runtime_state",
        "LaunchTeam",
        "s1a_legacy_external",
        996
    ),
    allow!(
        "lifecycle/launch.rs",
        "annotate_persisted_team_depth",
        "save_runtime_state",
        "AnnotateTeamDepth",
        "s1a_legacy_external",
        2779
    ),
    allow!(
        "lifecycle/launch.rs",
        "rollback_add_agent_atomic",
        "save_runtime_state_with_deleted_agents",
        "AgentRollback",
        "s1a_legacy_external",
        4005
    ),
    allow!(
        "lifecycle/launch.rs",
        "rollback_add_agent_atomic",
        "save_runtime_state_with_deleted_agents",
        "AgentRollback",
        "s1a_legacy_external",
        4032
    ),
    allow!(
        "lifecycle/launch.rs",
        "fork_agent_with_transport",
        "save_runtime_state_with_lifecycle_topology_authority",
        "ForkAgent",
        "s1a_legacy_external",
        4542
    ),
    allow!(
        "lifecycle/launch.rs",
        "rollback_fork_after_spawn",
        "save_runtime_state_with_deleted_agents",
        "AgentRollback",
        "s1a_legacy_external",
        4624
    ),
    allow!(
        "lifecycle/restart/agent.rs",
        "stop_agent_at_paths",
        "save_team_scoped_state_with_lifecycle_topology_authority",
        "StopAgent",
        "s1a_legacy_external",
        911
    ),
    allow!(
        "lifecycle/restart/agent.rs",
        "reset_agent_at_paths",
        "save_team_scoped_state_with_tombstone_lifecycle_topology_authority",
        "ResetAgent",
        "s1a_legacy_external",
        1355
    ),
    allow!(
        "lifecycle/restart/common.rs",
        "save_restart_projected_state_with_capture_backfill_skip",
        "save_team_scoped_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "RestartTeam",
        "s1b_migrate_first",
        633
    ),
    allow!(
        "lifecycle/restart/rebuild.rs",
        "save_restart_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "save_team_scoped_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "RestartTeam",
        "s1b_migrate_first",
        1528
    ),
    allow!(
        "lifecycle/restart/rebuild.rs",
        "save_restart_session_repairs",
        "save_team_scoped_state",
        "RestartSessionRepair",
        "s1b_migrate_first",
        1545
    ),
    allow!(
        "lifecycle/restart/rebuild.rs",
        "save_restart_session_repairs",
        "save_team_scoped_state",
        "RestartSessionRepair",
        "s1b_migrate_first",
        1555
    ),
    allow!(
        "lifecycle/restart/remove.rs",
        "remove_agent_inner",
        "save_team_scoped_state_with_deleted_agents",
        "RemoveAgent",
        "s1a_legacy_external",
        263
    ),
    allow!(
        "lifecycle/restart/remove.rs",
        "restore",
        "save_runtime_state",
        "AgentRollback",
        "s1a_legacy_external",
        786
    ),
    allow!(
        "mcp_server/lifecycle_tools/agent_ops.rs",
        "prepare_selected_team_state",
        "save_runtime_state",
        "McpLifecycleAgentOps",
        "s1a_legacy_external",
        385
    ),
    allow!(
        "mcp_server/lifecycle_tools/state_status.rs",
        "update_state",
        "save_team_scoped_state_reapplying_after_conflict",
        "McpUpdateStateNote",
        "s1a_legacy_external",
        29
    ),
    allow!(
        "mcp_server/lifecycle_tools/state_status.rs",
        "update_state_without_spec",
        "save_team_scoped_state_reapplying_after_conflict",
        "McpUpdateStateNote",
        "s1a_legacy_external",
        69
    ),
    allow!(
        "mcp_server/tools.rs",
        "assign_task",
        "save_runtime_state_reapplying_after_conflict",
        "McpAssignTask",
        "s1a_legacy_external",
        129
    ),
    allow!(
        "messaging/activity.rs",
        "detect_idle_fallbacks",
        "save_runtime_state_reapplying_after_conflict",
        "MessagingTurnArm",
        "s1a_legacy_external",
        83
    ),
    allow!(
        "messaging/delivery.rs",
        "save_scoped_state",
        "save_team_scoped_state",
        "MessagingDeliveryState",
        "s1a_legacy_external",
        2356
    ),
    allow!(
        "messaging/delivery.rs",
        "save_scoped_state",
        "save_runtime_state",
        "MessagingDeliveryState",
        "s1a_legacy_external",
        2358
    ),
    allow!(
        "messaging/delivery.rs",
        "save_scoped_state",
        "save_runtime_state",
        "MessagingDeliveryState",
        "s1a_legacy_external",
        2361
    ),
    allow!(
        "messaging/delivery.rs",
        "save_scoped_state_reapplying_after_conflict",
        "save_team_scoped_state_reapplying_after_conflict",
        "MessagingDeliveryState",
        "s1a_legacy_external",
        2389
    ),
    allow!(
        "messaging/delivery.rs",
        "save_scoped_state_reapplying_after_conflict",
        "save_runtime_state_reapplying_after_conflict",
        "MessagingDeliveryState",
        "s1a_legacy_external",
        2393
    ),
    allow!(
        "messaging/results.rs",
        "collect_scoped",
        "save_team_scoped_state_reapplying_after_conflict",
        "ResultCollection",
        "s1a_legacy_external",
        201
    ),
    allow!(
        "messaging/results.rs",
        "collect_scoped",
        "save_runtime_state_reapplying_after_conflict",
        "ResultCollection",
        "s1a_legacy_external",
        211
    ),
    allow!(
        "messaging/scheduler.rs",
        "stuck_cancel",
        "save_runtime_state_reapplying_after_conflict",
        "SchedulerSuppression",
        "s1a_legacy_external",
        259
    ),
    allow!(
        "state/persist.rs",
        "save_runtime_state",
        "save_runtime_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        207
    ),
    allow!(
        "state/persist.rs",
        "save_runtime_state_reapplying_after_conflict",
        "save_runtime_state",
        "repository_internal",
        "repository_internal",
        218
    ),
    allow!(
        "state/persist.rs",
        "save_runtime_state_reapplying_after_conflict",
        "save_runtime_state",
        "repository_internal",
        "repository_internal",
        223
    ),
    allow!(
        "state/persist.rs",
        "save_runtime_state_with_lifecycle_topology_authority",
        "save_runtime_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        234
    ),
    allow!(
        "state/persist.rs",
        "save_runtime_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "save_runtime_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        244
    ),
    allow!(
        "state/persist.rs",
        "save_runtime_state_with_deleted_agents",
        "save_runtime_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        259
    ),
    allow!(
        "state/persist.rs",
        "save_runtime_state_with_team_tombstoned_agents",
        "save_runtime_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        268
    ),
    allow!(
        "state/persist.rs",
        "save_runtime_state_with_team_tombstone_lifecycle_topology_authority",
        "save_runtime_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        284
    ),
    allow!(
        "state/persist.rs",
        "load_runtime_state",
        "save_runtime_state",
        "SelfMigration",
        "repository_internal",
        1127
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state",
        "save_team_scoped_state_with_deleted_agents",
        "repository_internal",
        "repository_internal",
        647
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_reapplying_after_conflict",
        "save_team_scoped_state",
        "repository_internal",
        "repository_internal",
        658
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_reapplying_after_conflict",
        "save_team_scoped_state",
        "repository_internal",
        "repository_internal",
        664
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_deleted_agents",
        "save_team_scoped_state_with_merge_exceptions",
        "repository_internal",
        "repository_internal",
        675
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_tombstone_lifecycle_topology_authority",
        "save_team_scoped_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        683
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_lifecycle_topology_authority",
        "save_team_scoped_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        691
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "save_team_scoped_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        700
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_exceptions",
        "save_team_scoped_state_with_merge_options",
        "repository_internal",
        "repository_internal",
        716
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_team_tombstone_lifecycle_topology_authority",
        "repository_internal",
        "repository_internal",
        768
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "repository_internal",
        "repository_internal",
        776
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_lifecycle_topology_authority",
        "repository_internal",
        "repository_internal",
        784
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "repository_internal",
        "repository_internal",
        791
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_deleted_agents",
        "repository_internal",
        "repository_internal",
        800
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_team_tombstoned_agents",
        "repository_internal",
        "repository_internal",
        802
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "repository_internal",
        "repository_internal",
        834
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_lifecycle_topology_authority",
        "repository_internal",
        "repository_internal",
        842
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_lifecycle_topology_authority_and_capture_backfill_skip",
        "repository_internal",
        "repository_internal",
        849
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_deleted_agents",
        "repository_internal",
        "repository_internal",
        857
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_team_tombstone_lifecycle_topology_authority",
        "repository_internal",
        "repository_internal",
        865
    ),
    allow!(
        "state/projection.rs",
        "save_team_scoped_state_with_merge_options",
        "save_runtime_state_with_team_tombstoned_agents",
        "repository_internal",
        "repository_internal",
        872
    ),
];
